version: 0.1
 
phases:
  pre_build:
    commands:
      - echo pip install
      - python --version
  build:
    commands:
      - echo Build started on `date`
      - apt-get install python-pip python-dev
      - pip install -r requirements.txt
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - "**/*"
  discard-paths: no