version: 0.1
 
phases:
  pre_build:
    commands:
      - echo pip install
      - cat /etc/system-release
      - yum -y install python-setuptools python-devel
      - easy_install pip      
  build:
    commands:
      - echo Build started on `date`
      - pip install -r requirements.txt -t .
      - echo zip -r artifact.zip ./*
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - "**/*"
  discard-paths: no